### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by pixelass** [atlassian/lerna-semantic-release#17]
There is no info about the install process. The readme describes the install process for `cz-lerna-changelog` instead of `lerna-semantic-release`
## Expected:

``` shell
npm i -D lerna-semantic-release
```
## Result

``` shell
09:51 $ npm i -D lerna-semantic-release
npm ERR! fetch failed [--> STANDARD NPM FAILURES <--]
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "-D" "lerna-semantic-release"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

```

Also: the package on npm seems empty: https://npmcdn.com/lerna-semantic-release@7.0.5

> Not found: main file "bin/semantic-release.js" in package lerna-semantic-release@7.0.5

**Comment by jpnelson** [comment]
Sorry for the delay, I'll be updating the changelog soon. The main field is actually wrong, I'll create a separate issue for that – the main field should be bin/lerna-semantic-release.js

**Comment by pixelass** [comment]
perfect. thx

**Comment by jpnelson** [comment]
I've added this information to the documentation.

Let me know if you have any other issues!
