### ISSUE TITLE
question: integration with GH + Travis

### ISSUE THREAD

**Issue by boneskull** [atlassian/lerna-semantic-release#31]
Hi,

So obviously this is an Atlassian effort, so I'm not expecting much support here.  :smile:

What I'm trying to do is have Travis CI push releases to GitHub.

However, `lerna-semantic-release` doesn't seem to have (or use?) GitHub credentials anywhere, so I don't know **what environment variable(s) to specify**, or **where code changes should be made** to support this.  I'd like to address this myself if a code change is necessary.

Here's an [example build](https://travis-ci.org/boneskull/big-iron/builds/160803074), with the relevant bit from line 537 forward.

Thanks!

**Comment by jpnelson** [comment]
No problem at all, happy to help :)

We have:

```
NPM_CONFIG_EMAIL 
NPM_CONFIG_USERNAME 
NPM_TOKEN 
GH_TOKEN 
RELEASE_GH_TOKEN
```

all set, and you can find the way that we set up git in lerna-semantic-release/.travis/before_install.sh .

Please let me know if you have more questions! We should really have this as part of the README.

**Comment by boneskull** [comment]
Thanks. I'll give that a shot and get back to you.

**Comment by jpnelson** [comment]
Cool, I'll close this – feel free to reopen if you have more questions :)
