### ISSUE TITLE
Changelog generation overwrites the whole file

### ISSUE THREAD

**Issue by Siilwyn** [atlassian/lerna-semantic-release#36]
It seems that the changelog generation overwrites the whole file and thus doesn't keep the older versions. This seems unusual, is this wanted and expected behaviour?

**Comment by jpnelson** [comment]
this is expected – it behaves differently to semantic release in this manner, as the old method relies on pushing to github. `lerna-semantic-release` is intended to be host-agnostic, and this seems like the best way at present.

That said, it'd be great if we could make an abstract way to push these changes somewhere (github release notes or another third party service).

Let me know if you have more questions or problems with this :)

**Comment by Siilwyn** [comment]
Well I don't see how appending changes to the file is not host-agnostic?

**Comment by jpnelson** [comment]
Sorry, to clarify: the old way was to not generate a file at all, and it to push the changelog generated to github. I raised https://github.com/atlassian/lerna-semantic-release/issues/52 to improve this
