### ISSUE TITLE
Is the package still supported?

### ISSUE THREAD

**Issue by vovacodes** [atlassian/lerna-semantic-release#46]
@jpnelson I've noticed that there were no changes in the project since October 2016, so I would like to ask is it still interesting for the authors to support it?
If you simply don't have enough time for it now, I would be happy to help with triaging and merging some of the PRs and issues

**Comment by jpnelson** [comment]
I'd love assistance with that – I'll mark some issues as "help wanted". It's definitely still in use and supported though :)
