### ISSUE TITLE
Release the new versions of lerna-semantic-release-*

### ISSUE THREAD

**Issue by vovacodes** [atlassian/lerna-semantic-release#49]
Is there anything that prevents us from releasing the updates to changed packages? The latest release was done in October 2016 according to github. Our team waits for the fixes and features a lot, can we help with releasing it somehow?

**Comment by jpnelson** [comment]
Apologies – not much had been merged to master recently, so I didn't realise that the build was failing on master. I've updated it now so it should release the changes soon

**Comment by jpnelson** [comment]
lerna-semantic-release@9.0.1 should bundle the latest changes, with the pre / post / perform / io packages also being updated.

One consequence is that the new lerna peer dependency is ^2.0.0-beta.31 . This made it a breaking change in pre, and in the main lerna-semantic-release package. Other than that, the API is the same.

Please raise a new issue if you're encountering more difficulty. Thanks for your help so far!

**Comment by vovacodes** [comment]
@jpnelson thanks a lot for addressing this!
