### ISSUE TITLE
Not relevant commits are included in CHANGELOG

### ISSUE THREAD

**Issue by vovacodes** [atlassian/lerna-semantic-release#57]
While using `lerna-semantic-release post` I've noticed that sometimes the commits that don't mention package `my-package` in their `affects:` line are still included in its CHANGELOG. I tried to debug that and the line that I suspect causes this issue is [this one](https://github.com/atlassian/lerna-semantic-release/blob/caribou/packages/lerna-semantic-release-post/index.js#L61):
```js
  if (!isRelevant && !commit.gitTags) {
    cb(null, null);
    return;
  }
```

@jpnelson do you know why `&& !commit.gitTags` is included into the condition? Shouldn't we always skip the commits that are not relevant to a certain package?

**Comment by jpnelson** [comment]
This should be fixed in 9.0.6 – I've refactored it to not use git tags, and instead use the git log – I anticipate that this will be more reliable in the long run, as the git log isn't mutable :)
